version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm install
  build:
    commands:
      - echo Copying files to build root for Elastic Beanstalk...
      - cp -r * ../

artifacts:
  files:
    - '**/*'
  base-directory: .
