version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd backend
      - npm install

  build:
    commands:
      - echo Preparing backend for Elastic Beanstalk deployment...
      - cp -r backend/* .

artifacts:
  files:
    - '**/*'
  base-directory: backend
